name: Autochangelog
on:
  pull_request_target:
    types: closed
    branches:
      - master

env:
  BASENAME: "chompstation"
  PRBODY: ${{ github.event.pull_request.body }}

jobs:
  autochangelog:
    name: Autochangelog
    runs-on: ubuntu-20.04
    concurrency: autochangelog_group
    if: github.event.pull_request.merged == true
    steps:
      - uses: /actions/checkout@v3
        with:
          ref: master
      - name: Update repository to master
        run: git pull "origin" master
      - name: Ensure +x on CI directory
        run: |
          chmod -R +x ./tools/ci
          chmod -R +x ./tools/GenerateChangelog
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Write PR body to file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: /tools/GenerateChangelog/prbody.txt
          write-mode: overwrite
          contents: $PRBODY
      - name: Generate Changelog
        run: |
          pip install pyyaml
          python tools/GenerateChangelog/ss13_autochangelog_ch.py \
            html/changelogs_ch \
            ${{ github.event.pull_request.number }} \
            '${{ github.event.pull_request.user.login }}' \
            prbody.txt
          python tools/GenerateChangelog/ss13_genchangelog_ch.py \
            html/changelogs_ch
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: /tools/GenerateChangelog/prbody.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic changelog generation for ${{ github.event.pull_request.number }}
          branch: ${{ github.event.pull_request.base.ref }}
          commit_user_name: Autochangelog Bot
